from fastapi import APIRouter, Depends, HTTPException, status
from typing import Dict, Any, List
from middleware.auth import require_role, check_project_access
from models.auth import UserRole
from config import (
    get_db,
    PROJECTS_COLLECTION,
    PROJECT_ESTIMATES_COLLECTION,
    PROGRESS_UPDATES_COLLECTION,
    SITE_IMAGES_COLLECTION
)

router = APIRouter(
    prefix="/api/customer",
    tags=["Customer"],
    dependencies=[Depends(require_role([UserRole.CUSTOMER.value]))]
)


@router.get("/dashboard")
async def get_customer_dashboard(current_user: Dict[str, Any] = Depends(require_role([UserRole.CUSTOMER.value]))):
    """
    Overview dashboard for the logged-in customer showing their assigned projects,
    active construction progress, total cost, carbon, and sustainability scores.
    """
    db = get_db()
    user_id = current_user.get("user_id")
    user_email = current_user.get("email")
    assigned_ids = current_user.get("assigned_project_ids", [])

    # Find projects assigned to this customer
    query = {
        "$or": [
            {"customer_id": user_id},
            {"customer_email": user_email},
            {"project_id": {"$in": assigned_ids}}
        ]
    }
    projects = await db[PROJECTS_COLLECTION].find(query, {"_id": 0}).to_list(50)

    if not projects:
        return {
            "has_project": False,
            "message": "No construction projects currently assigned to your account",
            "projects": []
        }

    # Use primary project
    primary_project = projects[0]
    pid = primary_project.get("project_id")

    # Fetch latest calculation estimate from existing collection
    estimate = await db[PROJECT_ESTIMATES_COLLECTION].find_one(
        {"project_id": pid},
        {"_id": 0}
    )

    # Fetch site images count
    images_count = await db[SITE_IMAGES_COLLECTION].count_documents({"project_id": pid})

    # Fetch recent updates
    recent_updates = await db[PROGRESS_UPDATES_COLLECTION].find(
        {"project_id": pid},
        {"_id": 0}
    ).sort("created_at", -1).limit(5).to_list(5)

    return {
        "has_project": True,
        "customer_name": current_user.get("name"),
        "primary_project": primary_project,
        "all_projects": projects,
        "latest_estimate": estimate,
        "images_count": images_count,
        "recent_updates": recent_updates
    }


@router.get("/projects")
async def get_customer_projects(current_user: Dict[str, Any] = Depends(require_role([UserRole.CUSTOMER.value]))):
    """List all projects assigned to the current customer."""
    db = get_db()
    user_id = current_user.get("user_id")
    user_email = current_user.get("email")
    assigned_ids = current_user.get("assigned_project_ids", [])

    query = {
        "$or": [
            {"customer_id": user_id},
            {"customer_email": user_email},
            {"project_id": {"$in": assigned_ids}}
        ]
    }
    projects = await db[PROJECTS_COLLECTION].find(query, {"_id": 0}).to_list(50)
    return projects


@router.get("/projects/{project_id}")
async def get_customer_project_detail(
    project_id: str,
    current_user: Dict[str, Any] = Depends(require_role([UserRole.CUSTOMER.value]))
):
    """Get full details of a specific project with strict tenant isolation."""
    project = await check_project_access(current_user, project_id)
    return project


@router.get("/projects/{project_id}/materials")
async def get_customer_materials(
    project_id: str,
    current_user: Dict[str, Any] = Depends(require_role([UserRole.CUSTOMER.value]))
):
    """Get material estimation breakdown generated by the Architect."""
    await check_project_access(current_user, project_id)
    db = get_db()
    estimate = await db[PROJECT_ESTIMATES_COLLECTION].find_one({"project_id": project_id}, {"_id": 0})
    if not estimate:
        return {"project_id": project_id, "materials": {}, "message": "No material estimation on record yet"}

    # Extract user-friendly material quantities
    quantities = estimate.get("material_quantities") or estimate.get("predicted_quantities") or {}
    return {
        "project_id": project_id,
        "materials": quantities,
        "total_cost": estimate.get("predicted_cost_inr"),
        "breakdown": estimate.get("cost_breakdown")
    }


@router.get("/projects/{project_id}/cost")
async def get_customer_cost(
    project_id: str,
    current_user: Dict[str, Any] = Depends(require_role([UserRole.CUSTOMER.value]))
):
    """Get project cost breakdown (materials, labor, equipment) calculated by the Architect."""
    await check_project_access(current_user, project_id)
    db = get_db()
    estimate = await db[PROJECT_ESTIMATES_COLLECTION].find_one({"project_id": project_id}, {"_id": 0})
    if not estimate:
        return {"project_id": project_id, "cost": None, "message": "Cost analysis pending"}

    return {
        "project_id": project_id,
        "predicted_cost_inr": estimate.get("predicted_cost_inr"),
        "cost_breakdown": estimate.get("cost_breakdown", {}),
        "cost_range": estimate.get("cost_range", {}),
        "currency": "INR",
        "created_at": estimate.get("created_at")
    }


@router.get("/projects/{project_id}/carbon")
async def get_customer_carbon(
    project_id: str,
    current_user: Dict[str, Any] = Depends(require_role([UserRole.CUSTOMER.value]))
):
    """Get carbon emissions calculated by the Architect."""
    await check_project_access(current_user, project_id)
    db = get_db()
    estimate = await db[PROJECT_ESTIMATES_COLLECTION].find_one({"project_id": project_id}, {"_id": 0})
    if not estimate:
        return {"project_id": project_id, "carbon": None, "message": "Carbon analysis pending"}

    carbon_data = estimate.get("carbon_data", {})
    return {
        "project_id": project_id,
        "carbon_data": carbon_data,
        "sustainability_score": estimate.get("sustainability_score"),
        "sustainability_tier": estimate.get("sustainability_tier")
    }


@router.get("/projects/{project_id}/sustainability")
async def get_customer_sustainability(
    project_id: str,
    current_user: Dict[str, Any] = Depends(require_role([UserRole.CUSTOMER.value]))
):
    """Get sustainability score, eco-friendly materials, reuse suggestions, and waste mitigation."""
    await check_project_access(current_user, project_id)
    db = get_db()
    estimate = await db[PROJECT_ESTIMATES_COLLECTION].find_one({"project_id": project_id}, {"_id": 0})
    if not estimate:
        return {"project_id": project_id, "sustainability": None, "message": "Sustainability evaluation pending"}

    return {
        "project_id": project_id,
        "sustainability_score": estimate.get("sustainability_score", 0),
        "sustainability_tier": estimate.get("sustainability_tier", "Standard"),
        "sustainable_alternatives": estimate.get("eco_suggestions", []),
        "material_reuse": estimate.get("reuse_suggestions", []),
        "waste_data": estimate.get("waste_data", {})
    }


@router.get("/projects/{project_id}/progress")
async def get_customer_progress(
    project_id: str,
    current_user: Dict[str, Any] = Depends(require_role([UserRole.CUSTOMER.value]))
):
    """Get current construction stage, completed stages, and timeline updates."""
    project = await check_project_access(current_user, project_id)
    db = get_db()
    updates = await db[PROGRESS_UPDATES_COLLECTION].find(
        {"project_id": project_id},
        {"_id": 0}
    ).sort("created_at", -1).to_list(50)

    stages = project.get("stages", [])
    overall_pct = project.get("overall_progress_pct", 0)
    current_stage = project.get("current_stage", "Planning")

    return {
        "project_id": project_id,
        "current_stage": current_stage,
        "overall_progress_pct": overall_pct,
        "stages": stages,
        "updates": updates
    }


@router.get("/projects/{project_id}/images")
async def get_customer_images(
    project_id: str,
    current_user: Dict[str, Any] = Depends(require_role([UserRole.CUSTOMER.value]))
):
    """Get site photos uploaded by the Architect for this project."""
    await check_project_access(current_user, project_id)
    db = get_db()
    images = await db[SITE_IMAGES_COLLECTION].find(
        {"project_id": project_id},
        {"_id": 0}
    ).sort("uploaded_at", -1).to_list(100)

    return images
